language: ruby
cache: bundler
rvm:
  - 2.1.1
gemfile:
  - Gemfile
  - gemfiles/rails-4.1.gemfile
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec
